version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: touch $BASH_ENV
      - run: echo 'export PATH=$HOME/repo/node_modules/.bin:$PATH' >> $BASH_ENV
      - run: source $BASH_ENV
      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}-{{ checksum "elm.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-{{ .Environment.CACHE_VERSION }}
      - run: | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
          if [ ! -d sysconfcpus/bin ];
          then
            git clone https://github.com/obmarg/libsysconfcpus.git;
            cd libsysconfcpus;
            ./configure --prefix=$HOME/repo/sysconfcpus;
            make && make install;
            cd ..;
          fi
      - run: yarn install
      - run: elm make
      - save_cache:
          paths:
            - node_modules
            - elm-stuff
            - tests/elm-stuff
            - sysconfcpus
            - $HOME/.elm
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}-{{ checksum "elm.json" }}
      - run: mv $HOME/repo/node_modules/.bin/elm $HOME/repo/node_modules/.bin/elm-old
      - run: printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 2"' '$HOME/repo/sysconfcpus/bin/sysconfcpus -n 2 elm-old "$@"' > $HOME/repo/node_modules/.bin/elm
      - run: chmod +x $HOME/repo/node_modules/.bin/elm
      - run: yarn test
      - run: elm-format --validate src
